workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - mostafashehab1228@gmail.com
        notify:
          success: true
          failure: true
